export enum RolUsuario {
  ADMINISTRADOR = 'ADMINISTRADOR',
  SUPERVISOR = 'SUPERVISOR',
  TECNICO = 'TECNICO',
  GESTOR_DE_VISITAS = 'GESTOR_DE_VISITAS',
  ANALISTA = 'ANALISTA',
}

export enum Prioridad {
  ALTA = 'ALTA',
  MEDIA = 'MEDIA',
  BAJA = 'BAJA',
}

export enum EstadoPunto {
  LIBRE = 'LIBRE',
  OCPP = 'OCPP',
}

export enum EstadoConexion {
  OK = 'OK',
  DESCONECTADO = 'DESCONECTADO',
  CONECTANDO = 'CONECTANDO',
}

export enum TipoPunto {
  PUNTO_CARGA = 'PUNTO_CARGA',
  ELECTROLINERA = 'ELECTROLINERA',
}

export enum TipoActividad {
  NOVEDAD = 'NOVEDAD',
  SEGUIMIENTO = 'SEGUIMIENTO',
}

export enum EstadoActividad {
  EN_REVISION = 'EN_REVISION',
  EN_PROCESO = 'EN_PROCESO',
  COMPLETADA = 'COMPLETADA',
}

export enum EstadoTurno {
  ABIERTO = 'ABIERTO',
  CERRADO = 'CERRADO',
}

export enum TipoActividadTecnica {
  INSTALACION = 'INSTALACION',
  MANTENIMIENTO_PREVENTIVO = 'MANTENIMIENTO_PREVENTIVO',
  MANTENIMIENTO_CORRECTIVO = 'MANTENIMIENTO_CORRECTIVO',
  VISITA_TECNICA = 'VISITA_TECNICA',
  REVISION_TECNICA = 'REVISION_TECNICA',
}

export enum EstadoActividadTecnica {
  ASIGNADA = 'ASIGNADA',
  EN_PROCESO = 'EN_PROCESO',
  COMPLETADA = 'COMPLETADA',
  OBSERVADA = 'OBSERVADA',
  CANCELADA = 'CANCELADA',
}

export enum EstadoPermisoAcceso {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  UPLOADED = 'UPLOADED',
}

export enum TipoInfraestructuraTecnica {
  PUNTO_CARGA = 'PUNTO_CARGA',
  ELECTROLINERA = 'ELECTROLINERA',
  BARRERA = 'BARRERA',
}

export enum AccionAuditoria {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export enum ExtraActivityType {
  QA_FUNCTIONAL = 'QA_FUNCTIONAL',
  QA_UI = 'QA_UI',
  BUG_REPORT = 'BUG_REPORT',
  BUG_FIX = 'BUG_FIX',
  BUG_VALIDATION = 'BUG_VALIDATION',
  PRODUCTION_REVIEW = 'PRODUCTION_REVIEW',
  OPERATIONAL_SUPPORT = 'OPERATIONAL_SUPPORT',
  DOCUMENTATION = 'DOCUMENTATION',
  MEETING = 'MEETING',
  TRAINING = 'TRAINING',
  TECHNICAL_ANALYSIS = 'TECHNICAL_ANALYSIS',
  EXTRA_MONITORING = 'EXTRA_MONITORING',
  OTHER = 'OTHER',
}

export enum WorkTimeCategory {
  DURING_SHIFT = 'DURING_SHIFT',
  OUTSIDE_SHIFT = 'OUTSIDE_SHIFT',
  WEEKEND_OR_HOLIDAY = 'WEEKEND_OR_HOLIDAY',
  EMERGENCY = 'EMERGENCY',
  MIXED = 'MIXED',
}

export enum ExtraActivityStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
}

export enum ExtraActivityPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}
